### ISSUE TITLE
#8 İki Data Source Kullanımı İçin Konfigrasyonu

### ISSUE THREAD

**Issue by emreylmaz** [Jira-Demo/Jira-Demo-BE#9]
Bu konfigrasyonun gerçekleşmesi şu yüzden önemlidir #2 bloke etmekte.

**Data Sourceların Konfigrasyonu**

![7c581829-ad77-4869-9a6d-59d27888bef1](https://github.com/Jira-Demo/Jira-Demo-BE/assets/29543060/8ead9882-1614-4a61-a5d9-f499f7679c6c)
![745e1466-1a69-4bed-bc02-ab4119d1647b](https://github.com/Jira-Demo/Jira-Demo-BE/assets/29543060/859d1fa8-dca6-4640-8998-1d0363dafb2d)

**Comment by emreylmaz** [comment]
Kontrol ve araştırmanız ricasıyla dostlarım.

FYI @burcubayik @EdaKevserDemir @okantasin @kadirdemirel

**Comment by burcubayik** [comment]
Projeyi yavaşlattığı için bu issue için daha sonra aksiyon alınacaktır.
